name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]

    steps:
      - uses: actions/checkout@v4
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          
      - name: Verify npm version
        run: |
          NPM_VERSION=$(npm --version)
          echo "NPM version: $NPM_VERSION"
          if ! npx semver $NPM_VERSION -r ">=8.0.0"; then
            echo "NPM version $NPM_VERSION does not meet requirement >=8.0.0"
            exit 1
          fi
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run linting
        run: npm run lint
        
      - name: Run tests with coverage
        run: npm run test:ci
        
      - name: Build
        run: npm run build
        
      - name: Upload coverage
        uses: codecov/codecov-action@v5
        if: matrix.node-version == '20.x'
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false
          files: ./coverage/lcov.info 